"""
Authors: Priyanshu Ranka,  Carter Ithier
Course: CS 7150 - Deep Learning
Semester: Spring 2026
Short description:  Script to run inference on demo images using 3 trained image captioning models (Baseline, ResNet+Transformer, ViT+Transformer) and display the generated captions for each model side by side. Models with their weights can be downloaded with the download_models.py script. Expects a folder of images and a vocab.pkl file generated by save_vocab.py.
"""

"""
demo.py

Runs inference on demo images using all 3 trained model architectures:
  1. Baseline  — ResNet50 encoder + LSTM decoder (Adam, c0 layer)
  2. ResNet+T  — ResNet50 encoder (spatial 7x7) + Transformer decoder
  3. ViT+T     — Pretrained ViT-B/16 encoder + Transformer decoder

For each image, displays a figure with one panel per model showing
the image and the generated caption.

Models with their weights can be downloaded with the download_models.py

Usage:
    python demo.py \
        --baseline_checkpoint   models/baseline_best_model.pt \
        --resnet_checkpoint     models/resnet_transformer_best.pt \
        --vit_checkpoint        models/vit_best_model.pt \
        --vocab_path            vocab.pkl \
        --image_dir             Images/

Directory structure expected:
    Images/        ← a few Flickr8k images here (or any images)
    vocab.pkl      ← generated by save_vocab.py
    demo.py
"""

import argparse
import math
import os
import pickle

import matplotlib
matplotlib.use("TkAgg")
import matplotlib.pyplot as plt
import numpy as np
import torch
import torchvision.transforms as transforms
from PIL import Image

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

IMG_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp"}


# ──────────────────────────────────────────────────────────────────────────────
# 1.  Image transform
# ──────────────────────────────────────────────────────────────────────────────

def get_transform():
    return transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                             std =[0.229, 0.224, 0.225]),
    ])


# ──────────────────────────────────────────────────────────────────────────────
# 2.  Model loaders
# ──────────────────────────────────────────────────────────────────────────────
def load_checkpoint(model, mode, path="./model.pt"):
    checkpoint = torch.load(path, map_location=device)
    model.load_state_dict(checkpoint['model_state_dict'])

    if mode == "eval":
        model.eval()
    else:
        model.train()

    return model

def load_baseline(vocab, checkpoint_path):
    from baseline.baseline_model_v2 import BaselineModel
    model = BaselineModel(vocab_size=len(vocab)).to(device)
    model = load_checkpoint(model, "eval", checkpoint_path)
    return model


def load_resnet_transformer(vocab, checkpoint_path):
    from resnet_transformer_decoder.resnet_transformer import ResnetTransformerModel
    model = ResnetTransformerModel(
        vocab=vocab,
        num_heads=8,
        trx_ff_dim=1024,
        num_decoder_cells=3,
        embed_dim=256,
        dropout=0.3,
        freeze=True,
    ).to(device)
    model = load_checkpoint(model, "eval", checkpoint_path)
    return model


def load_vit_transformer(vocab, checkpoint_path):
    from ViT_decoder.pytorch_pretrainined_enc_dec_model import VisionTransformerModel
    model = VisionTransformerModel(
        vocab=vocab,
        num_decoder_cells=6,
        trx_ff_dim=3072,
    ).to(device)
    model = load_checkpoint(model, "eval", checkpoint_path)
    return model


# ──────────────────────────────────────────────────────────────────────────────
# 3.  Inference helpers
# ──────────────────────────────────────────────────────────────────────────────

def run_baseline(model, vocab, image_tensor):
    with torch.no_grad():
        captions = model.generate(image_tensor, vocab) # list of words
    return " ".join(captions[0])


def run_resnet_transformer(model, vocab, image_tensor):
    with torch.no_grad():
        logits = model.forward(image_tensor)  # (1, L, vocab_size)
        indices = logits.argmax(dim=-1)[0].tolist()
        words = []
        for idx in indices:
            word = vocab.index_to_word.get(idx, "")
            if word in (vocab.EOS_TOKEN, vocab.PAD_TOKEN, vocab.SOS_TOKEN):
                break
            if word:
                words.append(word)
        return " ".join(words)


def run_vit_transformer(model, vocab, image_tensor):
    with torch.no_grad():
        logits = model.forward(image_tensor)  # (1, L, vocab_size)
        indices = logits.argmax(dim=-1)[0].tolist()
        words = []
        for idx in indices:
            word = vocab.index_to_word.get(idx, "")
            if word in (vocab.EOS_TOKEN, vocab.PAD_TOKEN, vocab.SOS_TOKEN):
                break
            if word:
                words.append(word)
        return " ".join(words)


# ──────────────────────────────────────────────────────────────────────────────
# 4.  Display
# ──────────────────────────────────────────────────────────────────────────────

def wrap_caption(caption, max_chars=45):
    """Simple word-wrap for caption display."""
    words = caption.split()
    lines, line = [], []
    for w in words:
        if sum(len(x) + 1 for x in line) + len(w) > max_chars:
            lines.append(" ".join(line))
            line = [w]
        else:
            line.append(w)
    if line:
        lines.append(" ".join(line))
    return "\n".join(lines)


def show_results(image_pil, captions_dict, img_name):
    """
    captions_dict: {"Baseline": "...", "ResNet+T": "...", "ViT+T": "..."}
    Displays one row: image on left, captions stacked on right.
    """
    fig, axes = plt.subplots(1, 2, figsize=(10, 4),
                             gridspec_kw={"width_ratios": [1, 1]})

    # left: image
    axes[0].imshow(np.array(image_pil.convert("RGB")))
    axes[0].axis("off")
    axes[0].set_title(img_name, fontsize=9, color="gray")

    # right: captions
    axes[1].axis("off")
    y = 0.85
    colors = {"Baseline": "#2196F3", "ResNet+T": "#4CAF50", "ViT+T": "#FF5722"}
    for model_name, caption in captions_dict.items():
        axes[1].text(0.0, y, f"{model_name}:", fontsize=10,
                     fontweight="bold", color=colors.get(model_name, "black"),
                     transform=axes[1].transAxes, va="top")
        axes[1].text(0.0, y - 0.08, wrap_caption(caption), fontsize=9,
                     color="black", transform=axes[1].transAxes, va="top",
                     style="italic")
        y -= 0.32

    plt.tight_layout()
    plt.show(block=True)


# ──────────────────────────────────────────────────────────────────────────────
# 5.  Main
# ──────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--baseline_checkpoint",
                        default="models/baseline_best_model.pt",
                        help="Path to baseline (ResNet+LSTM) checkpoint")
    parser.add_argument("--resnet_checkpoint",
                        default="models/resnet_transformer_best.pt",
                        help="Path to ResNet+Transformer checkpoint")
    parser.add_argument("--vit_checkpoint",
                        default="models/vit_best_model.pt",
                        help="Path to ViT+Transformer checkpoint")
    parser.add_argument("--vocab_path", default="vocab.pkl", 
                        help="Path to vocab.pkl")
    parser.add_argument("--image_dir",           default="Images/",
                        help="Folder of demo images (default: Images)")
    args = parser.parse_args()

    # load vocab
    with open(args.vocab_path, "rb") as f:
        vocab = pickle.load(f)

    # load models
    print("Loading Baseline (ResNet+LSTM)...")
    baseline_model = load_baseline(vocab, args.baseline_checkpoint)

    print("Loading ResNet+Transformer...")
    resnet_model = load_resnet_transformer(vocab, args.resnet_checkpoint)

    print("Loading ViT+Transformer...")
    vit_model = load_vit_transformer(vocab, args.vit_checkpoint)

    print("All models loaded.\n")

    # collect demo images
    transform   = get_transform()
    image_files = sorted([
        f for f in os.listdir(args.image_dir)
        if os.path.splitext(f)[1].lower() in IMG_EXTENSIONS
    ])

    if not image_files:
        print(f"No images found in {args.image_dir}. "
              f"Add a few .jpg images to the Images/ folder.")
        return

    # run inference on each image
    for img_name in image_files:
        img_path     = os.path.join(args.image_dir, img_name)
        image_pil    = Image.open(img_path).convert("RGB")
        image_tensor = transform(image_pil).unsqueeze(0).to(device)

        print(f"Image: {img_name}")

        c1 = run_baseline(baseline_model, vocab, image_tensor)
        c2 = run_resnet_transformer(resnet_model, vocab, image_tensor)
        c3 = run_vit_transformer(vit_model, vocab, image_tensor)

        print(f"  Baseline  : {c1}")
        print(f"  ResNet+T  : {c2}")
        print(f"  ViT+T     : {c3}\n")

        show_results(image_pil, {
            "Baseline":  c1,
            "ResNet+T":  c2,
            "ViT+T":     c3,
        }, img_name)


if __name__ == "__main__":
    main()